/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/-/test/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
         * @description ViewSet for simulating different API response scenarios.
         *
         *     Query Parameter:
         *         scenario (str): 'success', 'error', 'validation', or 'pagination'.
         */
    get: operations['__test_retrieve']
    put?: never
    /**
         * @description ViewSet for simulating different API response scenarios.
         *
         *     Query Parameter:
         *         scenario (str): 'success', 'error', 'validation', or 'pagination'.
         */
    post: operations['__test_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Authenticate with username/email and password to obtain access tokens. Returns user details along with JWT access and refresh tokens with expiration times. Authentication cookies are set automatically for secure token storage. */
    post: operations['api_v1_auth_login_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Logout user and invalidate authentication tokens. Blacklists JWT refresh tokens to prevent further use. Clears authentication cookies from the browser. Requires authentication to ensure only valid sessions can be logged out. */
    post: operations['api_v1_auth_logout_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/password/change/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Change the current user's password. Requires authentication. */
    post: operations['api_v1_auth_password_change_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/password/reset/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Send password reset instructions to the provided email address. If the email is registered, a secure reset link will be sent. The link expires after a limited time for security. */
    post: operations['api_v1_auth_password_reset_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/password/reset/confirm/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Complete the password reset process using the token from the reset email. Requires the UID and token from the email along with the new password. The token is single-use and expires for security. */
    post: operations['api_v1_auth_password_reset_confirm_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/registration/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Register a new user account. Users must verify their email address before the account is fully activated. */
    post: operations['api_v1_auth_registration_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/registration/resend-email/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Send a new email verification message to unverified email addresses. Only works for email addresses that are registered but not yet verified. */
    post: operations['api_v1_auth_registration_resend_email_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/registration/verify-email/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description GET method not allowed for email verification. */
    get: operations['api_v1_auth_registration_verify_email_retrieve']
    put?: never
    /** @description Confirm email address using the verification key sent via email. This activates the user account and allows login access. */
    post: operations['api_v1_auth_registration_verify_email_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/social/accounts/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description List all social accounts connected to the current user. Shows account details including provider, UID, and connection dates. */
    get: operations['api_v1_auth_social_accounts_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/social/accounts/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** @description Disconnect a social account from the current user. Removes the social account connection and prevents future logins via that provider. Requires authentication and the account must belong to the current user. */
    delete: operations['api_v1_auth_social_accounts_destroy']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/social/google/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Authenticate with Google using OAuth2/OpenID Connect authorization code to obtain access tokens. Returns user details along with JWT access and refresh tokens with expiration times. Authentication cookies are set automatically for secure token storage. */
    post: operations['api_v1_auth_social_google_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/social/google/connect/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Connect a Google account to the current user's account. This allows the user to login using their existing Google account in the future. Requires authentication and a valid OAuth2/OpenID Connect authorization code from Google. On success, the Google account is linked and can be used for future logins. */
    post: operations['api_v1_auth_social_google_connect_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/token/refresh/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Generate new JWT access tokens using refresh tokens. Refresh tokens can be provided in request data or extracted automatically from HTTP cookies. Returns new access tokens with updated expiration times. New tokens are automatically set in HTTP cookies for secure storage. */
    post: operations['api_v1_auth_token_refresh_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/token/verify/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
         * @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use.
         */
    post: operations['api_v1_auth_token_verify_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/user/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Retrieve the authenticated user's profile information including username, email, first name, and last name. Password fields are excluded. */
    get: operations['api_v1_auth_user_retrieve']
    /** @description Update the authenticated user's profile information. Allows modification of username, first name, and last name. Email field is read-only for security. */
    put: operations['api_v1_auth_user_update']
    post?: never
    delete?: never
    options?: never
    head?: never
    /** @description Partially update the authenticated user's profile information. Only provided fields will be updated. Email field is read-only. */
    patch: operations['api_v1_auth_user_partial_update']
    trace?: never
  }
  '/api/v1/users/me/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Retrieve or update the authenticated user's profile. */
    get: operations['api_v1_users_me_retrieve']
    /** @description Retrieve or update the authenticated user's profile. */
    put: operations['api_v1_users_me_update']
    post?: never
    delete?: never
    options?: never
    head?: never
    /** @description Retrieve or update the authenticated user's profile. */
    patch: operations['api_v1_users_me_partial_update']
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description JWT token refresh with cookie and request data support. */
    CookieTokenRefresh: {
      /** @description Will override cookie. */
      refresh?: string
      readonly access: string
      /** Format: date-time */
      readonly access_expiration: string
      /** Format: date-time */
      readonly refresh_expiration: string
    }
    /** @description Social authentication with Google OAuth credentials response. */
    GoogleSocialLogin: {
      readonly access: string
      readonly refresh: string
      /** Format: date-time */
      readonly access_expiration: string
      /** Format: date-time */
      readonly refresh_expiration: string
      readonly user: components['schemas']['User']
      code: string
    }
    /** @description JWT logout with refresh token blacklisting. */
    JWTLogout: {
      refresh?: string
      readonly detail: string
    }
    /** @description User authentication with credentials response. */
    Login: {
      readonly access: string
      readonly refresh: string
      /** Format: date-time */
      readonly access_expiration: string
      /** Format: date-time */
      readonly refresh_expiration: string
      readonly user: components['schemas']['User']
      /** Format: email */
      email: string
      password: string
    }
    PaginatedSocialAccountList: {
      /** @example 123 */
      count: number
      /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
      next?: string | null
      /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
      previous?: string | null
      results: components['schemas']['SocialAccount'][]
    }
    /** @description Password change for authenticated users. */
    PasswordChange: {
      new_password1: string
      new_password2: string
      readonly detail: string
    }
    /** @description Password reset request with email verification. */
    PasswordReset: {
      /** Format: email */
      email: string
      readonly detail: string
    }
    /** @description Password reset confirmation with new password. */
    PasswordResetConfirm: {
      new_password1: string
      new_password2: string
      uid: string
      token: string
      readonly detail: string
    }
    /** @description User profile information and updates. */
    PatchedUser: {
      /**
             * Id
             * Format: uuid
             */
      readonly pk?: string
      /** Format: email */
      readonly email?: string
      first_name?: string
      last_name?: string
    }
    /** @description User registration with email verification. */
    Register: {
      /** Format: email */
      email: string
      password1: string
      password2: string
      readonly detail: string
      first_name?: string
      last_name?: string
    }
    /** @description Request new email verification message. */
    ResendEmailVerification: {
      /** Format: email */
      email: string
      readonly detail: string
    }
    /**
         * @description Serializer for SocialAccount instances.
         *
         *     Provides a REST API representation of django-allauth SocialAccount
         *     objects, including provider information and connection metadata.
         */
    SocialAccount: {
      readonly id: number
      provider: string
      uid: string
      /** Format: date-time */
      readonly last_login: string
      /** Format: date-time */
      readonly date_joined: string
    }
    /**
         * @description Serializer for connecting social accounts to existing user accounts.
         *
         *     Handles OAuth authorization code exchange and connects the social
         *     account to the currently authenticated user's account.
         */
    SocialConnect: {
      code: string
      readonly detail: string
    }
    TokenVerify: {
      token: string
    }
    /** @description User profile information and updates. */
    User: {
      /**
             * Id
             * Format: uuid
             */
      readonly pk: string
      /** Format: email */
      readonly email: string
      first_name?: string
      last_name?: string
    }
    /** @description Email address verification with confirmation key. */
    VerifyEmail: {
      key: string
      readonly detail: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  __test_retrieve: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  __test_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  api_v1_auth_login_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Login']
        'application/x-www-form-urlencoded': components['schemas']['Login']
        'multipart/form-data': components['schemas']['Login']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Login']
        }
      }
    }
  }
  api_v1_auth_logout_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['JWTLogout']
        'application/x-www-form-urlencoded': components['schemas']['JWTLogout']
        'multipart/form-data': components['schemas']['JWTLogout']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JWTLogout']
        }
      }
    }
  }
  api_v1_auth_password_change_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordChange']
        'application/x-www-form-urlencoded': components['schemas']['PasswordChange']
        'multipart/form-data': components['schemas']['PasswordChange']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PasswordChange']
        }
      }
    }
  }
  api_v1_auth_password_reset_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordReset']
        'application/x-www-form-urlencoded': components['schemas']['PasswordReset']
        'multipart/form-data': components['schemas']['PasswordReset']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PasswordReset']
        }
      }
    }
  }
  api_v1_auth_password_reset_confirm_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetConfirm']
        'application/x-www-form-urlencoded': components['schemas']['PasswordResetConfirm']
        'multipart/form-data': components['schemas']['PasswordResetConfirm']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PasswordResetConfirm']
        }
      }
    }
  }
  api_v1_auth_registration_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Register']
        'application/x-www-form-urlencoded': components['schemas']['Register']
        'multipart/form-data': components['schemas']['Register']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Register']
        }
      }
    }
  }
  api_v1_auth_registration_resend_email_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ResendEmailVerification']
        'application/x-www-form-urlencoded': components['schemas']['ResendEmailVerification']
        'multipart/form-data': components['schemas']['ResendEmailVerification']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResendEmailVerification']
        }
      }
    }
  }
  api_v1_auth_registration_verify_email_retrieve: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Method not allowed */
      405: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  api_v1_auth_registration_verify_email_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyEmail']
        'application/x-www-form-urlencoded': components['schemas']['VerifyEmail']
        'multipart/form-data': components['schemas']['VerifyEmail']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['VerifyEmail']
        }
      }
    }
  }
  api_v1_auth_social_accounts_list: {
    parameters: {
      query?: {
        /** @description Which field to use when ordering the results. */
        ordering?: string
        /** @description A page number within the paginated result set. */
        page?: number
        /** @description Number of results to return per page. */
        page_size?: number
        /** @description A search term. */
        search?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PaginatedSocialAccountList']
        }
      }
    }
  }
  api_v1_auth_social_accounts_destroy: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this social account. */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  api_v1_auth_social_google_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GoogleSocialLogin']
        'application/x-www-form-urlencoded': components['schemas']['GoogleSocialLogin']
        'multipart/form-data': components['schemas']['GoogleSocialLogin']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GoogleSocialLogin']
        }
      }
    }
  }
  api_v1_auth_social_google_connect_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SocialConnect']
        'application/x-www-form-urlencoded': components['schemas']['SocialConnect']
        'multipart/form-data': components['schemas']['SocialConnect']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SocialConnect']
        }
      }
    }
  }
  api_v1_auth_token_refresh_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['CookieTokenRefresh']
        'application/x-www-form-urlencoded': components['schemas']['CookieTokenRefresh']
        'multipart/form-data': components['schemas']['CookieTokenRefresh']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CookieTokenRefresh']
        }
      }
    }
  }
  api_v1_auth_token_verify_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenVerify']
        'application/x-www-form-urlencoded': components['schemas']['TokenVerify']
        'multipart/form-data': components['schemas']['TokenVerify']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenVerify']
        }
      }
    }
  }
  api_v1_auth_user_retrieve: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
    }
  }
  api_v1_auth_user_update: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['User']
        'application/x-www-form-urlencoded': components['schemas']['User']
        'multipart/form-data': components['schemas']['User']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
    }
  }
  api_v1_auth_user_partial_update: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedUser']
        'application/x-www-form-urlencoded': components['schemas']['PatchedUser']
        'multipart/form-data': components['schemas']['PatchedUser']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
    }
  }
  api_v1_users_me_retrieve: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
    }
  }
  api_v1_users_me_update: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['User']
        'application/x-www-form-urlencoded': components['schemas']['User']
        'multipart/form-data': components['schemas']['User']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
    }
  }
  api_v1_users_me_partial_update: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedUser']
        'application/x-www-form-urlencoded': components['schemas']['PatchedUser']
        'multipart/form-data': components['schemas']['PatchedUser']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
    }
  }
}
