/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from 'zod'
import type { Json } from './../types/database.types'

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema)
    ])
    .nullable()
)

export const authAalLevelSchema = z.enum(['aal1', 'aal2', 'aal3'])

export const authCodeChallengeMethodSchema = z.enum(['s256', 'plain'])

export const authFactorStatusSchema = z.enum(['unverified', 'verified'])

export const authFactorTypeSchema = z.enum(['totp', 'webauthn', 'phone'])

export const authOauthAuthorizationStatusSchema = z.enum([
  'pending',
  'approved',
  'denied',
  'expired'
])

export const authOauthClientTypeSchema = z.enum(['public', 'confidential'])

export const authOauthRegistrationTypeSchema = z.enum(['dynamic', 'manual'])

export const authOauthResponseTypeSchema = z.enum(['code'])

export const authOneTimeTokenTypeSchema = z.enum([
  'confirmation_token',
  'reauthentication_token',
  'recovery_token',
  'email_change_token_new',
  'email_change_token_current',
  'phone_change_token'
])

export const authAuditLogEntriesRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.string(),
  instance_id: z.string().nullable(),
  ip_address: z.string(),
  payload: jsonSchema.nullable()
})

export const authAuditLogEntriesInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string(),
  instance_id: z.string().optional().nullable(),
  ip_address: z.string().optional(),
  payload: jsonSchema.optional().nullable()
})

export const authAuditLogEntriesUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  instance_id: z.string().optional().nullable(),
  ip_address: z.string().optional(),
  payload: jsonSchema.optional().nullable()
})

export const authCustomOauthProvidersRowSchema = z.object({
  acceptable_client_ids: z.array(z.string()),
  attribute_mapping: jsonSchema,
  authorization_params: jsonSchema,
  authorization_url: z.string().nullable(),
  cached_discovery: jsonSchema.nullable(),
  client_id: z.string(),
  client_secret: z.string(),
  created_at: z.string(),
  discovery_cached_at: z.string().nullable(),
  discovery_url: z.string().nullable(),
  email_optional: z.boolean(),
  enabled: z.boolean(),
  id: z.string(),
  identifier: z.string(),
  issuer: z.string().nullable(),
  jwks_uri: z.string().nullable(),
  name: z.string(),
  pkce_enabled: z.boolean(),
  provider_type: z.string(),
  scopes: z.array(z.string()),
  skip_nonce_check: z.boolean(),
  token_url: z.string().nullable(),
  updated_at: z.string(),
  userinfo_url: z.string().nullable()
})

export const authCustomOauthProvidersInsertSchema = z.object({
  acceptable_client_ids: z.array(z.string()).optional(),
  attribute_mapping: jsonSchema.optional(),
  authorization_params: jsonSchema.optional(),
  authorization_url: z.string().optional().nullable(),
  cached_discovery: jsonSchema.optional().nullable(),
  client_id: z.string(),
  client_secret: z.string(),
  created_at: z.string().optional(),
  discovery_cached_at: z.string().optional().nullable(),
  discovery_url: z.string().optional().nullable(),
  email_optional: z.boolean().optional(),
  enabled: z.boolean().optional(),
  id: z.string().optional(),
  identifier: z.string(),
  issuer: z.string().optional().nullable(),
  jwks_uri: z.string().optional().nullable(),
  name: z.string(),
  pkce_enabled: z.boolean().optional(),
  provider_type: z.string(),
  scopes: z.array(z.string()).optional(),
  skip_nonce_check: z.boolean().optional(),
  token_url: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  userinfo_url: z.string().optional().nullable()
})

export const authCustomOauthProvidersUpdateSchema = z.object({
  acceptable_client_ids: z.array(z.string()).optional(),
  attribute_mapping: jsonSchema.optional(),
  authorization_params: jsonSchema.optional(),
  authorization_url: z.string().optional().nullable(),
  cached_discovery: jsonSchema.optional().nullable(),
  client_id: z.string().optional(),
  client_secret: z.string().optional(),
  created_at: z.string().optional(),
  discovery_cached_at: z.string().optional().nullable(),
  discovery_url: z.string().optional().nullable(),
  email_optional: z.boolean().optional(),
  enabled: z.boolean().optional(),
  id: z.string().optional(),
  identifier: z.string().optional(),
  issuer: z.string().optional().nullable(),
  jwks_uri: z.string().optional().nullable(),
  name: z.string().optional(),
  pkce_enabled: z.boolean().optional(),
  provider_type: z.string().optional(),
  scopes: z.array(z.string()).optional(),
  skip_nonce_check: z.boolean().optional(),
  token_url: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  userinfo_url: z.string().optional().nullable()
})

export const authFlowStateRowSchema = z.object({
  auth_code: z.string().nullable(),
  auth_code_issued_at: z.string().nullable(),
  authentication_method: z.string(),
  code_challenge: z.string().nullable(),
  code_challenge_method: authCodeChallengeMethodSchema.nullable(),
  created_at: z.string().nullable(),
  email_optional: z.boolean(),
  id: z.string(),
  invite_token: z.string().nullable(),
  linking_target_id: z.string().nullable(),
  oauth_client_state_id: z.string().nullable(),
  provider_access_token: z.string().nullable(),
  provider_refresh_token: z.string().nullable(),
  provider_type: z.string(),
  referrer: z.string().nullable(),
  updated_at: z.string().nullable(),
  user_id: z.string().nullable()
})

export const authFlowStateInsertSchema = z.object({
  auth_code: z.string().optional().nullable(),
  auth_code_issued_at: z.string().optional().nullable(),
  authentication_method: z.string(),
  code_challenge: z.string().optional().nullable(),
  code_challenge_method: authCodeChallengeMethodSchema.optional().nullable(),
  created_at: z.string().optional().nullable(),
  email_optional: z.boolean().optional(),
  id: z.string(),
  invite_token: z.string().optional().nullable(),
  linking_target_id: z.string().optional().nullable(),
  oauth_client_state_id: z.string().optional().nullable(),
  provider_access_token: z.string().optional().nullable(),
  provider_refresh_token: z.string().optional().nullable(),
  provider_type: z.string(),
  referrer: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional().nullable()
})

export const authFlowStateUpdateSchema = z.object({
  auth_code: z.string().optional().nullable(),
  auth_code_issued_at: z.string().optional().nullable(),
  authentication_method: z.string().optional(),
  code_challenge: z.string().optional().nullable(),
  code_challenge_method: authCodeChallengeMethodSchema.optional().nullable(),
  created_at: z.string().optional().nullable(),
  email_optional: z.boolean().optional(),
  id: z.string().optional(),
  invite_token: z.string().optional().nullable(),
  linking_target_id: z.string().optional().nullable(),
  oauth_client_state_id: z.string().optional().nullable(),
  provider_access_token: z.string().optional().nullable(),
  provider_refresh_token: z.string().optional().nullable(),
  provider_type: z.string().optional(),
  referrer: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional().nullable()
})

export const authIdentitiesRowSchema = z.object({
  created_at: z.string().nullable(),
  email: z.string().nullable(),
  id: z.string(),
  identity_data: jsonSchema,
  last_sign_in_at: z.string().nullable(),
  provider: z.string(),
  provider_id: z.string(),
  updated_at: z.string().nullable(),
  user_id: z.string()
})

export const authIdentitiesInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  id: z.string().optional(),
  identity_data: jsonSchema,
  last_sign_in_at: z.string().optional().nullable(),
  provider: z.string(),
  provider_id: z.string(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string()
})

export const authIdentitiesUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  id: z.string().optional(),
  identity_data: jsonSchema.optional(),
  last_sign_in_at: z.string().optional().nullable(),
  provider: z.string().optional(),
  provider_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional()
})

export const authIdentitiesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('identities_user_id_fkey'),
    columns: z.tuple([z.literal('user_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('users'),
    referencedColumns: z.tuple([z.literal('id')])
  })
])

export const authInstancesRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.string(),
  raw_base_config: z.string().nullable(),
  updated_at: z.string().nullable(),
  uuid: z.string().nullable()
})

export const authInstancesInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string(),
  raw_base_config: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  uuid: z.string().optional().nullable()
})

export const authInstancesUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  raw_base_config: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  uuid: z.string().optional().nullable()
})

export const authMfaAmrClaimsRowSchema = z.object({
  authentication_method: z.string(),
  created_at: z.string(),
  id: z.string(),
  session_id: z.string(),
  updated_at: z.string()
})

export const authMfaAmrClaimsInsertSchema = z.object({
  authentication_method: z.string(),
  created_at: z.string(),
  id: z.string(),
  session_id: z.string(),
  updated_at: z.string()
})

export const authMfaAmrClaimsUpdateSchema = z.object({
  authentication_method: z.string().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  session_id: z.string().optional(),
  updated_at: z.string().optional()
})

export const authMfaAmrClaimsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('mfa_amr_claims_session_id_fkey'),
    columns: z.tuple([z.literal('session_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('sessions'),
    referencedColumns: z.tuple([z.literal('id')])
  })
])

export const authMfaChallengesRowSchema = z.object({
  created_at: z.string(),
  factor_id: z.string(),
  id: z.string(),
  ip_address: z.unknown(),
  otp_code: z.string().nullable(),
  verified_at: z.string().nullable(),
  web_authn_session_data: jsonSchema.nullable()
})

export const authMfaChallengesInsertSchema = z.object({
  created_at: z.string(),
  factor_id: z.string(),
  id: z.string(),
  ip_address: z.unknown(),
  otp_code: z.string().optional().nullable(),
  verified_at: z.string().optional().nullable(),
  web_authn_session_data: jsonSchema.optional().nullable()
})

export const authMfaChallengesUpdateSchema = z.object({
  created_at: z.string().optional(),
  factor_id: z.string().optional(),
  id: z.string().optional(),
  ip_address: z.unknown().optional(),
  otp_code: z.string().optional().nullable(),
  verified_at: z.string().optional().nullable(),
  web_authn_session_data: jsonSchema.optional().nullable()
})

export const authMfaChallengesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('mfa_challenges_auth_factor_id_fkey'),
    columns: z.tuple([z.literal('factor_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('mfa_factors'),
    referencedColumns: z.tuple([z.literal('id')])
  })
])

export const authMfaFactorsRowSchema = z.object({
  created_at: z.string(),
  factor_type: authFactorTypeSchema,
  friendly_name: z.string().nullable(),
  id: z.string(),
  last_challenged_at: z.string().nullable(),
  last_webauthn_challenge_data: jsonSchema.nullable(),
  phone: z.string().nullable(),
  secret: z.string().nullable(),
  status: authFactorStatusSchema,
  updated_at: z.string(),
  user_id: z.string(),
  web_authn_aaguid: z.string().nullable(),
  web_authn_credential: jsonSchema.nullable()
})

export const authMfaFactorsInsertSchema = z.object({
  created_at: z.string(),
  factor_type: authFactorTypeSchema,
  friendly_name: z.string().optional().nullable(),
  id: z.string(),
  last_challenged_at: z.string().optional().nullable(),
  last_webauthn_challenge_data: jsonSchema.optional().nullable(),
  phone: z.string().optional().nullable(),
  secret: z.string().optional().nullable(),
  status: authFactorStatusSchema,
  updated_at: z.string(),
  user_id: z.string(),
  web_authn_aaguid: z.string().optional().nullable(),
  web_authn_credential: jsonSchema.optional().nullable()
})

export const authMfaFactorsUpdateSchema = z.object({
  created_at: z.string().optional(),
  factor_type: authFactorTypeSchema.optional(),
  friendly_name: z.string().optional().nullable(),
  id: z.string().optional(),
  last_challenged_at: z.string().optional().nullable(),
  last_webauthn_challenge_data: jsonSchema.optional().nullable(),
  phone: z.string().optional().nullable(),
  secret: z.string().optional().nullable(),
  status: authFactorStatusSchema.optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
  web_authn_aaguid: z.string().optional().nullable(),
  web_authn_credential: jsonSchema.optional().nullable()
})

export const authMfaFactorsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('mfa_factors_user_id_fkey'),
    columns: z.tuple([z.literal('user_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('users'),
    referencedColumns: z.tuple([z.literal('id')])
  })
])

export const authOauthAuthorizationsRowSchema = z.object({
  approved_at: z.string().nullable(),
  authorization_code: z.string().nullable(),
  authorization_id: z.string(),
  client_id: z.string(),
  code_challenge: z.string().nullable(),
  code_challenge_method: authCodeChallengeMethodSchema.nullable(),
  created_at: z.string(),
  expires_at: z.string(),
  id: z.string(),
  nonce: z.string().nullable(),
  redirect_uri: z.string(),
  resource: z.string().nullable(),
  response_type: authOauthResponseTypeSchema,
  scope: z.string(),
  state: z.string().nullable(),
  status: authOauthAuthorizationStatusSchema,
  user_id: z.string().nullable()
})

export const authOauthAuthorizationsInsertSchema = z.object({
  approved_at: z.string().optional().nullable(),
  authorization_code: z.string().optional().nullable(),
  authorization_id: z.string(),
  client_id: z.string(),
  code_challenge: z.string().optional().nullable(),
  code_challenge_method: authCodeChallengeMethodSchema.optional().nullable(),
  created_at: z.string().optional(),
  expires_at: z.string().optional(),
  id: z.string(),
  nonce: z.string().optional().nullable(),
  redirect_uri: z.string(),
  resource: z.string().optional().nullable(),
  response_type: authOauthResponseTypeSchema.optional(),
  scope: z.string(),
  state: z.string().optional().nullable(),
  status: authOauthAuthorizationStatusSchema.optional(),
  user_id: z.string().optional().nullable()
})

export const authOauthAuthorizationsUpdateSchema = z.object({
  approved_at: z.string().optional().nullable(),
  authorization_code: z.string().optional().nullable(),
  authorization_id: z.string().optional(),
  client_id: z.string().optional(),
  code_challenge: z.string().optional().nullable(),
  code_challenge_method: authCodeChallengeMethodSchema.optional().nullable(),
  created_at: z.string().optional(),
  expires_at: z.string().optional(),
  id: z.string().optional(),
  nonce: z.string().optional().nullable(),
  redirect_uri: z.string().optional(),
  resource: z.string().optional().nullable(),
  response_type: authOauthResponseTypeSchema.optional(),
  scope: z.string().optional(),
  state: z.string().optional().nullable(),
  status: authOauthAuthorizationStatusSchema.optional(),
  user_id: z.string().optional().nullable()
})

export const authOauthAuthorizationsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('oauth_authorizations_client_id_fkey'),
    columns: z.tuple([z.literal('client_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('oauth_clients'),
    referencedColumns: z.tuple([z.literal('id')])
  }),
  z.object({
    foreignKeyName: z.literal('oauth_authorizations_user_id_fkey'),
    columns: z.tuple([z.literal('user_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('users'),
    referencedColumns: z.tuple([z.literal('id')])
  })
])

export const authOauthClientStatesRowSchema = z.object({
  code_verifier: z.string().nullable(),
  created_at: z.string(),
  id: z.string(),
  provider_type: z.string()
})

export const authOauthClientStatesInsertSchema = z.object({
  code_verifier: z.string().optional().nullable(),
  created_at: z.string(),
  id: z.string(),
  provider_type: z.string()
})

export const authOauthClientStatesUpdateSchema = z.object({
  code_verifier: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  provider_type: z.string().optional()
})

export const authOauthClientsRowSchema = z.object({
  client_name: z.string().nullable(),
  client_secret_hash: z.string().nullable(),
  client_type: authOauthClientTypeSchema,
  client_uri: z.string().nullable(),
  created_at: z.string(),
  deleted_at: z.string().nullable(),
  grant_types: z.string(),
  id: z.string(),
  logo_uri: z.string().nullable(),
  redirect_uris: z.string(),
  registration_type: authOauthRegistrationTypeSchema,
  token_endpoint_auth_method: z.string(),
  updated_at: z.string()
})

export const authOauthClientsInsertSchema = z.object({
  client_name: z.string().optional().nullable(),
  client_secret_hash: z.string().optional().nullable(),
  client_type: authOauthClientTypeSchema.optional(),
  client_uri: z.string().optional().nullable(),
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  grant_types: z.string(),
  id: z.string(),
  logo_uri: z.string().optional().nullable(),
  redirect_uris: z.string(),
  registration_type: authOauthRegistrationTypeSchema,
  token_endpoint_auth_method: z.string(),
  updated_at: z.string().optional()
})

export const authOauthClientsUpdateSchema = z.object({
  client_name: z.string().optional().nullable(),
  client_secret_hash: z.string().optional().nullable(),
  client_type: authOauthClientTypeSchema.optional(),
  client_uri: z.string().optional().nullable(),
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  grant_types: z.string().optional(),
  id: z.string().optional(),
  logo_uri: z.string().optional().nullable(),
  redirect_uris: z.string().optional(),
  registration_type: authOauthRegistrationTypeSchema.optional(),
  token_endpoint_auth_method: z.string().optional(),
  updated_at: z.string().optional()
})

export const authOauthConsentsRowSchema = z.object({
  client_id: z.string(),
  granted_at: z.string(),
  id: z.string(),
  revoked_at: z.string().nullable(),
  scopes: z.string(),
  user_id: z.string()
})

export const authOauthConsentsInsertSchema = z.object({
  client_id: z.string(),
  granted_at: z.string().optional(),
  id: z.string(),
  revoked_at: z.string().optional().nullable(),
  scopes: z.string(),
  user_id: z.string()
})

export const authOauthConsentsUpdateSchema = z.object({
  client_id: z.string().optional(),
  granted_at: z.string().optional(),
  id: z.string().optional(),
  revoked_at: z.string().optional().nullable(),
  scopes: z.string().optional(),
  user_id: z.string().optional()
})

export const authOauthConsentsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('oauth_consents_client_id_fkey'),
    columns: z.tuple([z.literal('client_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('oauth_clients'),
    referencedColumns: z.tuple([z.literal('id')])
  }),
  z.object({
    foreignKeyName: z.literal('oauth_consents_user_id_fkey'),
    columns: z.tuple([z.literal('user_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('users'),
    referencedColumns: z.tuple([z.literal('id')])
  })
])

export const authOneTimeTokensRowSchema = z.object({
  created_at: z.string(),
  id: z.string(),
  relates_to: z.string(),
  token_hash: z.string(),
  token_type: authOneTimeTokenTypeSchema,
  updated_at: z.string(),
  user_id: z.string()
})

export const authOneTimeTokensInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.string(),
  relates_to: z.string(),
  token_hash: z.string(),
  token_type: authOneTimeTokenTypeSchema,
  updated_at: z.string().optional(),
  user_id: z.string()
})

export const authOneTimeTokensUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  relates_to: z.string().optional(),
  token_hash: z.string().optional(),
  token_type: authOneTimeTokenTypeSchema.optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional()
})

export const authOneTimeTokensRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('one_time_tokens_user_id_fkey'),
    columns: z.tuple([z.literal('user_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('users'),
    referencedColumns: z.tuple([z.literal('id')])
  })
])

export const authRefreshTokensRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.number(),
  instance_id: z.string().nullable(),
  parent: z.string().nullable(),
  revoked: z.boolean().nullable(),
  session_id: z.string().nullable(),
  token: z.string().nullable(),
  updated_at: z.string().nullable(),
  user_id: z.string().nullable()
})

export const authRefreshTokensInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.number().optional(),
  instance_id: z.string().optional().nullable(),
  parent: z.string().optional().nullable(),
  revoked: z.boolean().optional().nullable(),
  session_id: z.string().optional().nullable(),
  token: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional().nullable()
})

export const authRefreshTokensUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.number().optional(),
  instance_id: z.string().optional().nullable(),
  parent: z.string().optional().nullable(),
  revoked: z.boolean().optional().nullable(),
  session_id: z.string().optional().nullable(),
  token: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional().nullable()
})

export const authRefreshTokensRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('refresh_tokens_session_id_fkey'),
    columns: z.tuple([z.literal('session_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('sessions'),
    referencedColumns: z.tuple([z.literal('id')])
  })
])

export const authSamlProvidersRowSchema = z.object({
  attribute_mapping: jsonSchema.nullable(),
  created_at: z.string().nullable(),
  entity_id: z.string(),
  id: z.string(),
  metadata_url: z.string().nullable(),
  metadata_xml: z.string(),
  name_id_format: z.string().nullable(),
  sso_provider_id: z.string(),
  updated_at: z.string().nullable()
})

export const authSamlProvidersInsertSchema = z.object({
  attribute_mapping: jsonSchema.optional().nullable(),
  created_at: z.string().optional().nullable(),
  entity_id: z.string(),
  id: z.string(),
  metadata_url: z.string().optional().nullable(),
  metadata_xml: z.string(),
  name_id_format: z.string().optional().nullable(),
  sso_provider_id: z.string(),
  updated_at: z.string().optional().nullable()
})

export const authSamlProvidersUpdateSchema = z.object({
  attribute_mapping: jsonSchema.optional().nullable(),
  created_at: z.string().optional().nullable(),
  entity_id: z.string().optional(),
  id: z.string().optional(),
  metadata_url: z.string().optional().nullable(),
  metadata_xml: z.string().optional(),
  name_id_format: z.string().optional().nullable(),
  sso_provider_id: z.string().optional(),
  updated_at: z.string().optional().nullable()
})

export const authSamlProvidersRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('saml_providers_sso_provider_id_fkey'),
    columns: z.tuple([z.literal('sso_provider_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('sso_providers'),
    referencedColumns: z.tuple([z.literal('id')])
  })
])

export const authSamlRelayStatesRowSchema = z.object({
  created_at: z.string().nullable(),
  flow_state_id: z.string().nullable(),
  for_email: z.string().nullable(),
  id: z.string(),
  redirect_to: z.string().nullable(),
  request_id: z.string(),
  sso_provider_id: z.string(),
  updated_at: z.string().nullable()
})

export const authSamlRelayStatesInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  flow_state_id: z.string().optional().nullable(),
  for_email: z.string().optional().nullable(),
  id: z.string(),
  redirect_to: z.string().optional().nullable(),
  request_id: z.string(),
  sso_provider_id: z.string(),
  updated_at: z.string().optional().nullable()
})

export const authSamlRelayStatesUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  flow_state_id: z.string().optional().nullable(),
  for_email: z.string().optional().nullable(),
  id: z.string().optional(),
  redirect_to: z.string().optional().nullable(),
  request_id: z.string().optional(),
  sso_provider_id: z.string().optional(),
  updated_at: z.string().optional().nullable()
})

export const authSamlRelayStatesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('saml_relay_states_flow_state_id_fkey'),
    columns: z.tuple([z.literal('flow_state_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('flow_state'),
    referencedColumns: z.tuple([z.literal('id')])
  }),
  z.object({
    foreignKeyName: z.literal('saml_relay_states_sso_provider_id_fkey'),
    columns: z.tuple([z.literal('sso_provider_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('sso_providers'),
    referencedColumns: z.tuple([z.literal('id')])
  })
])

export const authSchemaMigrationsRowSchema = z.object({
  version: z.string()
})

export const authSchemaMigrationsInsertSchema = z.object({
  version: z.string()
})

export const authSchemaMigrationsUpdateSchema = z.object({
  version: z.string().optional()
})

export const authSessionsRowSchema = z.object({
  aal: authAalLevelSchema.nullable(),
  created_at: z.string().nullable(),
  factor_id: z.string().nullable(),
  id: z.string(),
  ip: z.unknown(),
  not_after: z.string().nullable(),
  oauth_client_id: z.string().nullable(),
  refresh_token_counter: z.number().nullable(),
  refresh_token_hmac_key: z.string().nullable(),
  refreshed_at: z.string().nullable(),
  scopes: z.string().nullable(),
  tag: z.string().nullable(),
  updated_at: z.string().nullable(),
  user_agent: z.string().nullable(),
  user_id: z.string()
})

export const authSessionsInsertSchema = z.object({
  aal: authAalLevelSchema.optional().nullable(),
  created_at: z.string().optional().nullable(),
  factor_id: z.string().optional().nullable(),
  id: z.string(),
  ip: z.unknown().optional(),
  not_after: z.string().optional().nullable(),
  oauth_client_id: z.string().optional().nullable(),
  refresh_token_counter: z.number().optional().nullable(),
  refresh_token_hmac_key: z.string().optional().nullable(),
  refreshed_at: z.string().optional().nullable(),
  scopes: z.string().optional().nullable(),
  tag: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_agent: z.string().optional().nullable(),
  user_id: z.string()
})

export const authSessionsUpdateSchema = z.object({
  aal: authAalLevelSchema.optional().nullable(),
  created_at: z.string().optional().nullable(),
  factor_id: z.string().optional().nullable(),
  id: z.string().optional(),
  ip: z.unknown().optional(),
  not_after: z.string().optional().nullable(),
  oauth_client_id: z.string().optional().nullable(),
  refresh_token_counter: z.number().optional().nullable(),
  refresh_token_hmac_key: z.string().optional().nullable(),
  refreshed_at: z.string().optional().nullable(),
  scopes: z.string().optional().nullable(),
  tag: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_agent: z.string().optional().nullable(),
  user_id: z.string().optional()
})

export const authSessionsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('sessions_oauth_client_id_fkey'),
    columns: z.tuple([z.literal('oauth_client_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('oauth_clients'),
    referencedColumns: z.tuple([z.literal('id')])
  }),
  z.object({
    foreignKeyName: z.literal('sessions_user_id_fkey'),
    columns: z.tuple([z.literal('user_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('users'),
    referencedColumns: z.tuple([z.literal('id')])
  })
])

export const authSsoDomainsRowSchema = z.object({
  created_at: z.string().nullable(),
  domain: z.string(),
  id: z.string(),
  sso_provider_id: z.string(),
  updated_at: z.string().nullable()
})

export const authSsoDomainsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  domain: z.string(),
  id: z.string(),
  sso_provider_id: z.string(),
  updated_at: z.string().optional().nullable()
})

export const authSsoDomainsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  domain: z.string().optional(),
  id: z.string().optional(),
  sso_provider_id: z.string().optional(),
  updated_at: z.string().optional().nullable()
})

export const authSsoDomainsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('sso_domains_sso_provider_id_fkey'),
    columns: z.tuple([z.literal('sso_provider_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('sso_providers'),
    referencedColumns: z.tuple([z.literal('id')])
  })
])

export const authSsoProvidersRowSchema = z.object({
  created_at: z.string().nullable(),
  disabled: z.boolean().nullable(),
  id: z.string(),
  resource_id: z.string().nullable(),
  updated_at: z.string().nullable()
})

export const authSsoProvidersInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  disabled: z.boolean().optional().nullable(),
  id: z.string(),
  resource_id: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable()
})

export const authSsoProvidersUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  disabled: z.boolean().optional().nullable(),
  id: z.string().optional(),
  resource_id: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable()
})

export const authUsersRowSchema = z.object({
  aud: z.string().nullable(),
  banned_until: z.string().nullable(),
  confirmation_sent_at: z.string().nullable(),
  confirmation_token: z.string().nullable(),
  confirmed_at: z.string().nullable(),
  created_at: z.string().nullable(),
  deleted_at: z.string().nullable(),
  email: z.string().nullable(),
  email_change: z.string().nullable(),
  email_change_confirm_status: z.number().nullable(),
  email_change_sent_at: z.string().nullable(),
  email_change_token_current: z.string().nullable(),
  email_change_token_new: z.string().nullable(),
  email_confirmed_at: z.string().nullable(),
  encrypted_password: z.string().nullable(),
  id: z.string(),
  instance_id: z.string().nullable(),
  invited_at: z.string().nullable(),
  is_anonymous: z.boolean(),
  is_sso_user: z.boolean(),
  is_super_admin: z.boolean().nullable(),
  last_sign_in_at: z.string().nullable(),
  phone: z.string().nullable(),
  phone_change: z.string().nullable(),
  phone_change_sent_at: z.string().nullable(),
  phone_change_token: z.string().nullable(),
  phone_confirmed_at: z.string().nullable(),
  raw_app_meta_data: jsonSchema.nullable(),
  raw_user_meta_data: jsonSchema.nullable(),
  reauthentication_sent_at: z.string().nullable(),
  reauthentication_token: z.string().nullable(),
  recovery_sent_at: z.string().nullable(),
  recovery_token: z.string().nullable(),
  role: z.string().nullable(),
  updated_at: z.string().nullable()
})

export const authUsersInsertSchema = z.object({
  aud: z.string().optional().nullable(),
  banned_until: z.string().optional().nullable(),
  confirmation_sent_at: z.string().optional().nullable(),
  confirmation_token: z.string().optional().nullable(),
  confirmed_at: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  email_change: z.string().optional().nullable(),
  email_change_confirm_status: z.number().optional().nullable(),
  email_change_sent_at: z.string().optional().nullable(),
  email_change_token_current: z.string().optional().nullable(),
  email_change_token_new: z.string().optional().nullable(),
  email_confirmed_at: z.string().optional().nullable(),
  encrypted_password: z.string().optional().nullable(),
  id: z.string(),
  instance_id: z.string().optional().nullable(),
  invited_at: z.string().optional().nullable(),
  is_anonymous: z.boolean().optional(),
  is_sso_user: z.boolean().optional(),
  is_super_admin: z.boolean().optional().nullable(),
  last_sign_in_at: z.string().optional().nullable(),
  phone: z.string().optional().nullable(),
  phone_change: z.string().optional().nullable(),
  phone_change_sent_at: z.string().optional().nullable(),
  phone_change_token: z.string().optional().nullable(),
  phone_confirmed_at: z.string().optional().nullable(),
  raw_app_meta_data: jsonSchema.optional().nullable(),
  raw_user_meta_data: jsonSchema.optional().nullable(),
  reauthentication_sent_at: z.string().optional().nullable(),
  reauthentication_token: z.string().optional().nullable(),
  recovery_sent_at: z.string().optional().nullable(),
  recovery_token: z.string().optional().nullable(),
  role: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable()
})

export const authUsersUpdateSchema = z.object({
  aud: z.string().optional().nullable(),
  banned_until: z.string().optional().nullable(),
  confirmation_sent_at: z.string().optional().nullable(),
  confirmation_token: z.string().optional().nullable(),
  confirmed_at: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  email_change: z.string().optional().nullable(),
  email_change_confirm_status: z.number().optional().nullable(),
  email_change_sent_at: z.string().optional().nullable(),
  email_change_token_current: z.string().optional().nullable(),
  email_change_token_new: z.string().optional().nullable(),
  email_confirmed_at: z.string().optional().nullable(),
  encrypted_password: z.string().optional().nullable(),
  id: z.string().optional(),
  instance_id: z.string().optional().nullable(),
  invited_at: z.string().optional().nullable(),
  is_anonymous: z.boolean().optional(),
  is_sso_user: z.boolean().optional(),
  is_super_admin: z.boolean().optional().nullable(),
  last_sign_in_at: z.string().optional().nullable(),
  phone: z.string().optional().nullable(),
  phone_change: z.string().optional().nullable(),
  phone_change_sent_at: z.string().optional().nullable(),
  phone_change_token: z.string().optional().nullable(),
  phone_confirmed_at: z.string().optional().nullable(),
  raw_app_meta_data: jsonSchema.optional().nullable(),
  raw_user_meta_data: jsonSchema.optional().nullable(),
  reauthentication_sent_at: z.string().optional().nullable(),
  reauthentication_token: z.string().optional().nullable(),
  recovery_sent_at: z.string().optional().nullable(),
  recovery_token: z.string().optional().nullable(),
  role: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable()
})

export const authWebauthnChallengesRowSchema = z.object({
  challenge_type: z.string(),
  created_at: z.string(),
  expires_at: z.string(),
  id: z.string(),
  session_data: jsonSchema,
  user_id: z.string().nullable()
})

export const authWebauthnChallengesInsertSchema = z.object({
  challenge_type: z.string(),
  created_at: z.string().optional(),
  expires_at: z.string(),
  id: z.string().optional(),
  session_data: jsonSchema,
  user_id: z.string().optional().nullable()
})

export const authWebauthnChallengesUpdateSchema = z.object({
  challenge_type: z.string().optional(),
  created_at: z.string().optional(),
  expires_at: z.string().optional(),
  id: z.string().optional(),
  session_data: jsonSchema.optional(),
  user_id: z.string().optional().nullable()
})

export const authWebauthnChallengesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('webauthn_challenges_user_id_fkey'),
    columns: z.tuple([z.literal('user_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('users'),
    referencedColumns: z.tuple([z.literal('id')])
  })
])

export const authWebauthnCredentialsRowSchema = z.object({
  aaguid: z.string().nullable(),
  attestation_type: z.string(),
  backed_up: z.boolean(),
  backup_eligible: z.boolean(),
  created_at: z.string(),
  credential_id: z.string(),
  friendly_name: z.string(),
  id: z.string(),
  last_used_at: z.string().nullable(),
  public_key: z.string(),
  sign_count: z.number(),
  transports: jsonSchema,
  updated_at: z.string(),
  user_id: z.string()
})

export const authWebauthnCredentialsInsertSchema = z.object({
  aaguid: z.string().optional().nullable(),
  attestation_type: z.string().optional(),
  backed_up: z.boolean().optional(),
  backup_eligible: z.boolean().optional(),
  created_at: z.string().optional(),
  credential_id: z.string(),
  friendly_name: z.string().optional(),
  id: z.string().optional(),
  last_used_at: z.string().optional().nullable(),
  public_key: z.string(),
  sign_count: z.number().optional(),
  transports: jsonSchema.optional(),
  updated_at: z.string().optional(),
  user_id: z.string()
})

export const authWebauthnCredentialsUpdateSchema = z.object({
  aaguid: z.string().optional().nullable(),
  attestation_type: z.string().optional(),
  backed_up: z.boolean().optional(),
  backup_eligible: z.boolean().optional(),
  created_at: z.string().optional(),
  credential_id: z.string().optional(),
  friendly_name: z.string().optional(),
  id: z.string().optional(),
  last_used_at: z.string().optional().nullable(),
  public_key: z.string().optional(),
  sign_count: z.number().optional(),
  transports: jsonSchema.optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional()
})

export const authWebauthnCredentialsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('webauthn_credentials_user_id_fkey'),
    columns: z.tuple([z.literal('user_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('users'),
    referencedColumns: z.tuple([z.literal('id')])
  })
])

export const authEmailArgsSchema = z.never()

export const authEmailReturnsSchema = z.string()

export const authJwtArgsSchema = z.never()

export const authJwtReturnsSchema = jsonSchema

export const authRoleArgsSchema = z.never()

export const authRoleReturnsSchema = z.string()

export const authUidArgsSchema = z.never()

export const authUidReturnsSchema = z.string()

export const publicGuardiansRowSchema = z.object({
  cnic: z.string().nullable(),
  created_at: z.string(),
  email: z.string().nullable(),
  emergency_name: z.string().nullable(),
  emergency_phone: z.string().nullable(),
  emergency_relationship: z.string().nullable(),
  id: z.string(),
  is_whatsapp: z.boolean().nullable(),
  name: z.string().nullable(),
  phone: z.string().nullable(),
  relationship: z.string().nullable()
})

export const publicGuardiansInsertSchema = z.object({
  cnic: z.string().optional().nullable(),
  created_at: z.string().optional(),
  email: z.string().optional().nullable(),
  emergency_name: z.string().optional().nullable(),
  emergency_phone: z.string().optional().nullable(),
  emergency_relationship: z.string().optional().nullable(),
  id: z.string(),
  is_whatsapp: z.boolean().optional().nullable(),
  name: z.string().optional().nullable(),
  phone: z.string().optional().nullable(),
  relationship: z.string().optional().nullable()
})

export const publicGuardiansUpdateSchema = z.object({
  cnic: z.string().optional().nullable(),
  created_at: z.string().optional(),
  email: z.string().optional().nullable(),
  emergency_name: z.string().optional().nullable(),
  emergency_phone: z.string().optional().nullable(),
  emergency_relationship: z.string().optional().nullable(),
  id: z.string().optional(),
  is_whatsapp: z.boolean().optional().nullable(),
  name: z.string().optional().nullable(),
  phone: z.string().optional().nullable(),
  relationship: z.string().optional().nullable()
})

export const publicGuardiansRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('guardian_id_fkey'),
    columns: z.tuple([z.literal('id')]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal('profiles'),
    referencedColumns: z.tuple([z.literal('id')])
  })
])

export const publicProfilesRowSchema = z.object({
  address: z.string().nullable(),
  avatar_url: z.string().nullable(),
  blood_group: z.string().nullable(),
  city: z.string().nullable(),
  cnic: z.string().nullable(),
  dob: z.string().nullable(),
  first_name: z.string().nullable(),
  full_name: z.string().nullable(),
  gender: z.string().nullable(),
  id: z.string(),
  last_name: z.string().nullable(),
  province: z.string().nullable()
})

export const publicProfilesInsertSchema = z.object({
  address: z.string().optional().nullable(),
  avatar_url: z.string().optional().nullable(),
  blood_group: z.string().optional().nullable(),
  city: z.string().optional().nullable(),
  cnic: z.string().optional().nullable(),
  dob: z.string().optional().nullable(),
  first_name: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  gender: z.string().optional().nullable(),
  id: z.string(),
  last_name: z.string().optional().nullable(),
  province: z.string().optional().nullable()
})

export const publicProfilesUpdateSchema = z.object({
  address: z.string().optional().nullable(),
  avatar_url: z.string().optional().nullable(),
  blood_group: z.string().optional().nullable(),
  city: z.string().optional().nullable(),
  cnic: z.string().optional().nullable(),
  dob: z.string().optional().nullable(),
  first_name: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  gender: z.string().optional().nullable(),
  id: z.string().optional(),
  last_name: z.string().optional().nullable(),
  province: z.string().optional().nullable()
})
